### ISSUE TITLE
BUG-how set particular time zone for the schedular.. if i'm designing stock market if deployed application to some other zone all scheduler work deployed time zone 

### ISSUE THREAD

**Issue by rabbu480** [Miksus/rocketry#145]
**BUG-how to set the particular time zone for the schedule**
how set the particular time zone for the schedular.. if I designed a stock market & deployed an application to some other zone all scheduler work deployed time zone. 

**Expected behavior**
Should have somewhere to set the time zone.

**Comment by Miksus** [comment]
This is a duplicate issue (see #113) (related PR #147). I'm currently working on the issue but cannot yet say when I'm done.
