### ISSUE TITLE
Conditions: cron "0/20 * * * *" is not same as "*/20 * * * *"

### ISSUE THREAD

**Issue by nikitazavadsky** [Miksus/rocketry#227]
**Describe the bug**
"0/20 * * * *" cron pattern launches my tasks hourly while "*/20 * * * *" launches tasks every 20 minutes

There is a screenshot of my log stats from heroku for 0/20 * * * * pattern

![image](https://github.com/Miksus/rocketry/assets/72129830/62fcd631-d5fd-4f34-8a05-b1000313a913)

there is one for */20 * * * *

![image](https://github.com/Miksus/rocketry/assets/72129830/1be18c94-80bc-42be-a9d5-ef7134b6e08e)

**Expected behavior**
I expect these patterns to behave in the same way

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Python version: 3.11.6
 
 requirements.txt:
 
 pydantic==1.10.10
fastapi
rocketry
requests
boto3
uvicorn[standard]

**Comment by zzl221000** [comment]
Hey, man, "0/20 * * * * *" is not standard cron. Heroku ignores "/20".

[rontab.guru](https://crontab.guru/#0/20_*_*_*_*)

**Comment by nikitazavadsky** [comment]
@zzl221000 

Thanks for your response. I've already changed it to the standart pattern and it works as expected
