### ISSUE TITLE
ENH: Add async support

### ISSUE THREAD

**Issue by sorasful** [Miksus/rocketry#28]
Hi there ! Thanks for your work ! 

**Is your feature request related to a problem? Please describe.**
It'll be great to be able to run tasks that use async code.

**Describe the solution you'd like**
A transparent asyncio support to be able to run async code.

**Comment by gaby** [comment]
👍🏻 for this feature!

**Comment by Miksus** [comment]
Thanks! Indeed I think this would be great. We could have a new execution type that works like:

```python
@app.task("daily", execution="async")
def do_things():
    ....
```

 Should not be too hard to implement either. We need it here: https://github.com/Miksus/red-engine/blob/ba26ec20992a6b3e774d7d8c92e67bc7beea437d/redengine/core/task.py#L349-L365

And then we could do something similar as with the thread execution but just with async loop: https://github.com/Miksus/red-engine/blob/ba26ec20992a6b3e774d7d8c92e67bc7beea437d/redengine/core/task.py#L489-L501

I'm on a bit of baby steps on Asyncio but sounds to be as easy as the thread support.

After that, I think we could start thinking of turning the scheduling system itself as async.

**Comment by ddanier** [comment]
Would love to see this, too. This would enable using Rocketry for my FastAPI projects. 👍

**Comment by gaby** [comment]
@Miksus Should be able to close this one, right?

**Comment by Miksus** [comment]
Oh, that's indeed true. This is already part of the framework.
