### ISSUE TITLE
Logging docs have a typo

### ISSUE THREAD

**Issue by sijaira** [Miksus/rocketry#66]
**Is it corrected in the latest version (master branch)?**
no

Latest version of the docs: https://rocketry.readthedocs.io/en/latest/

**Location in the documentation you wish to improve**
https://rocketry.readthedocs.io/en/latest/handbooks/logging.html#

**Describe the problem**

The line below causes an error:

> logging.addHander(handler)

**Suggestion for the fix**

It should be:

> logger.addHandler(handler)

**Comment by Miksus** [comment]
Oh, true. Thanks for spotting! 

I'll fix this in the upcoming days (unless anyone else wants).

**Comment by Miksus** [comment]
Fixed in #72
